name: 'Terraform apply tagging and versioning'

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string
        description: 'Target Environment (sit, uat, production)'
      working_dir:          
        required: true
        type: string
      is_apply:
        required: true
        type: boolean
        description: 'Set to true to run ONLY terraform apply from artifact'

env:  
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

jobs:
  core-engine:
    name: 'Execute TF Ops'
    runs-on: windows-latest
    environment: ${{ inputs.target_env }}
    
    permissions:
      id-token: write
      contents: write

    steps:
      - name: 'Checkout Source Code'
        uses: actions/checkout@v4

      - name: 'Azure Login (OIDC)'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false 
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: 'Terraform Initialization'
        shell: pwsh
        run: |          
          $envName = "${{ inputs.target_env }}"         
          if ($envName -eq "development") { $envName = "dev" }          
          $workspaceName = "infra-$envName"
          Write-Output "Targeting Workspace: $workspaceName"     
          "TF_WORKSPACE=$workspaceName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          $env:TF_WORKSPACE = $workspaceName             
          
          terraform -chdir="${{ inputs.working_dir }}" init       
         
      - name: 'Download Terraform Plan Artifact'
        if: ${{ inputs.is_apply == true }}
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: ${{ github.workspace }}/${{ inputs.working_dir }}

      - name: 'Execute Terraform Apply'
        if: ${{ inputs.is_apply == true }}
        shell: pwsh
        run: |
          terraform -chdir="${{ inputs.working_dir }}" apply -auto-approve tfplan.binary  
          
  tag-infrastructure:
    name: 'Tagging and Versioning'
    needs: core-engine
    if: ${{ inputs.is_apply == true && inputs.target_env == 'production' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         WITH_V: true
