name: 'Terraform Lint Template'

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string
        description: 'Target Environment (sit, uat, production)'
      working_dir:          
        required: true
        type: string
      is_apply:
        required: true
        type: boolean
        description: 'Set to true to run ONLY terraform apply from artifact'

env:  
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

jobs:
  core-engine:
    name: 'Execute TF Ops'
    runs-on: windows-latest
    environment: ${{ inputs.target_env }}
    
    permissions:
      id-token: write
      contents: write

    steps:
      - name: 'Checkout Source Code'
        uses: actions/checkout@v4

      - name: 'Azure Login (OIDC)'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          
      - name: 'Setup TFLint'
        if: ${{ inputs.is_apply == false }}
        uses: terraform-linters/setup-tflint@v6.2.2
        with:
          tflint_version: latest
      - name: 'Run TFLint Scan'
        if: ${{ inputs.is_apply == false }}
        shell: pwsh
        run: |
          tflint --init --chdir="${{ inputs.working_dir }}"
          tflint -f compact --chdir="${{ inputs.working_dir }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 